#!/bin/bash
#
# Title: pushover
#
# Description:
#   Send messages using the Pushover service, pushover.net. An account is
#   required to use this service.
#
# Credits:  None
#
# Usage:
#   Either source this script and call pushover() with the message as first arg.
#    or
#   Call this script directly with the message as first argument.
#   Either way, two environment variables must exist and be non-empty:
#     PO_USER_TOKEN - the token used to identify the Pushover user;
#     PO_APP_TOKEN  - the token used to distinguish the application.
#   If these are not set, the script exits and no push message is sent.
#
# Maintainer: dr.j.osborne@gmail.com
#
# License: MIT, see LICENSE file in repository root
#

: "${PO_USER_TOKEN:?PO_USER_TOKEN env var must be set to use PushOver service}"

: "${PO_APP_TOKEN:?PO_APP_TOKEN env var must be set to use PushOver service}"

# $1 Message
function pushover()
{
    local USER_MESSAGE="message=$(date -u "+%Y-%m-%d %H:%M:%S"): ${1-Message placeholder text}"

    local PUSHOVER_RESPONSE=$(curl -s --form-string "token=$PO_APP_TOKEN" \
        --form-string "user=$PO_USER_TOKEN" \
        --form-string "$USER_MESSAGE" \
        https://api.pushover.net/1/messages.json)

    CURL_EXIT_STATUS=$?

    echo "Curl exited with $CURL_EXIT_STATUS; Pushover response $PUSHOVER_RESPONSE"
}

# A smart bit of trickery to see if this script is running as exe or as source
if [[ "$0" == "$BASH_SOURCE" ]]; then
    # we haven't been sourced, so run as executable
    pushover "$@"
    exit $?
fi
